name: CI/CD Pipeline for Housing Predictor

on:
  push:
    branches: [ rs_05021 ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest
    - name: Lint with flake8
      run: flake8 src/ --max-line-length=100 --extend-ignore=E203
    - name: Test with pytest
      run: pytest src/ -v  # Add tests in src/ if needed

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/housing-predictor:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    steps:
    - name: Local Deployment Simulation
      run: echo "Simulating local deployment with docker run -p 8000:8000 housing-predictor"
