name: CI Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted Linux runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run a script
      run: echo "Hello from GitHub-hosted runner!"
