name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: housing-api
  DOCKER_HUB_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASS: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Run flake8 linter
        run: |
          flake8 src/ --max-line-length=120

      - name: Run unit tests
        run: |
          pytest tests/

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: lint-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${DOCKER_HUB_PASS}" | docker login -u "${DOCKER_HUB_USER}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_HUB_USER/$IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $DOCKER_HUB_USER/$IMAGE_NAME:latest

  deploy:
    name: Deploy to Local/EC2
    runs-on: ubuntu-latest  # Use `self-hosted` if deploying to EC2 directly
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull and Run Docker container
        run: |
          docker pull $DOCKER_HUB_USER/$IMAGE_NAME:latest
          docker stop housing-api || true
          docker rm housing-api || true
          docker run -d --name housing-api -p 8000:8000 $DOCKER_HUB_USER/$IMAGE_NAME:latest
